### ISSUE TITLE
Could you backport this to 1.20.1?

### ISSUE THREAD

**Issue by SimplyTadpole** [crafter312/dimensional-weather#3]
Hello! I'm making a liminal space/beta ARG-style modpack that involves the player accessing different instances of Overworld-style dimensions, some of which are meant to feel liminal in appearance, and I also ran into the issue of weather not applying per dimensions.

Many of the mods I'm using for the modpack aren't available for 1.20.4, so I wanted to ask if you'd be willing to backport this to 1.20.1 so I could also make use of this?

**Comment by crafter312** [comment]
I haven't looked at it yet, but I don't imagine that would be too much of a problem!

In fact, given the simplicity of this mod, there's a small chance that it might already work in 1.20.1 (I haven't tested that yet, though; I'm not sure if you've tried it either, but it would be worth testing if you haven't already). If it works in 1.20.1 as is, I'll update the version numbers to reflect that. If not, I'll do a quick backport.

**Comment by SimplyTadpole** [comment]
Well, I tested it but Minecraft wouldn't launch because it's flagged as requiring 1.20.4 instead of 1.20.1; I'm not sure if it's possible to bypass that :c

**Comment by crafter312** [comment]
Ah you're right, I forgot about that. I'll have to do some testing myself then.

**Comment by crafter312** [comment]
Just made a 1.20.1 version and did a quick test to make sure it works, so that should be posted on github/curseforge/modrinth. Let me know if there are any other issues. I hope your modpack development goes well!

**Comment by SimplyTadpole** [comment]
Thank you for the speedy backporting! I appreciate it a lot, and thanks for your kindness c:

Sadly, I still can't use it as my modpack depends on Quilt for some Quilt-only mods, and currently the latest version of Quilt Loader for 1.20.1 provides the Fabric Loader version 0.15.7; your mod requires version 0.15.11, and thus crashes. :/

I don't want to bug you too much so I understand if you'd rather not, but do you think you could make the mod depend on Fabric Loader 0.15.7 instead, or does it require features only available on 0.15.11?

**Comment by crafter312** [comment]
I've never used Quilt before, so I didn't think to test that. That should be an easy fix though! The mod doesn't require Fabric Loader 0.15.11, that is just the version the Fabric site gave me to copy over while backporting.

**Comment by crafter312** [comment]
Fabric loader version has been changed, so hopefully this issue has been fixed. Let me know if there are any other issues.

**Comment by SimplyTadpole** [comment]
Hi! Really sorry to bug you again, but unfortunately the mod seems to be making the game crash...

Here's my crash report file, if it can be of any use: [crash-2024-06-11_23.06.26.8353-quilt_loader.txt](https://github.com/user-attachments/files/15812452/crash-2024-06-11_23.06.26.8353-quilt_loader.txt)

**Comment by crafter312** [comment]
I'll have to take some time and look closer at the Quilt compatibility then. I'm not super familiar with Quilt, so it might take me a bit of time to figure out. Have you tried loading the mod only by itself in Quilt? Just to make sure it's a problem with the mod itself and not a compatibility issue with other mods in Quilt.

**Comment by crafter312** [comment]
Ok, so I think I managed to figure this out. By downloading the Quilted Fabric API, I was able to get my mod working properly in Quilt for Minecraft 1.20.1. I just used the latest version of QFAPI for Minecraft 1.20.1:

https://www.curseforge.com/minecraft/mc-mods/qsl/files/5420724

Could you test this out and let me know if it works for you?

**Comment by SimplyTadpole** [comment]
That did the trick! Thank you so much!

Initially, it didn't seem to work, but upgrading to Quilt Loader v0.26.0 and QFAIP v7.5.0-0.92.2 made it function c:
